In [1]:
import numpy as np
a = np.array([
    [1, 2, 3,],
    [4, 5, 6,],
    [7, 8, 9]
])

print(a)
print(a[0])
print(a[0,1])
print([0,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
2
[0, 2]


In [3]:
# slicing numpy

a = np.array([
    [1, 2, 3,],
    [4, 5, 6,],
    [7, 8, 9]
])

print(a[0:2])   # start : stop
print(a[0:2, 0:2])   # [baris, kolom]



[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]


In [5]:
# mengubah nilai

a[1] = [10,23,22]
a[2] = 11
print(a)

[[ 1  2  3]
 [10 23 22]
 [11 11 11]]


In [7]:
data = np.array([
    ["Denis", "Scratch", 8],
    ["Frank", "Python", 18],
    ["Roger", "Unity", 15]
])
print(a[0])
print(a[1])
print(a[2])
print(a[0:1])
data[0,1] = "Roblox"
print(data)

[1 2 3]
[10 23 22]
[11 11 11]
[[1 2 3]]
[['Denis' 'Roblox' '8']
 ['Frank' 'Python' '18']
 ['Roger' 'Unity' '15']]
