In [ ]:
# function void, return, parameter,rekursiv (memanggil dirinya sendiri) function di dalam function
# function args & kwargs

def hitung(*a):
  result = 0
  for i in a:
    result += i
  return(result)

simpan = hitung(1,2,3,4,5)
print(simpan)

15


In [4]:
def hitung2(**a):
  for i in a.keys():
    print("key =",i)

  for z in a.values():
    print("value =",z)

  for i,z in a.items():
    print("key =",i ,"value =",z)

hitung2(nama = "agung", alamat = "denpasar")




key = nama
key = alamat
value = agung
value = denpasar
key = nama value = agung
key = alamat value = denpasar


In [6]:
# funtion lamda = function satu baris

def tambah(a, b):
  return a + b

tambah2 = tambah(10, 20)

tambah3 =(lambda a, b: a + b)(10, 20)

print(tambah2)
print(tambah3)


30
30


In [9]:
def hitung(*a):
  result = 0
  for i in a:
    result += i
  return(result)

simpan = hitung(1,2,3,4,5,6,7,8,9,10)
print(simpan)

rata_rata = (lambda a, b : a/b)(simpan, 10)
print(rata_rata)

55
5.5


In [11]:
# numpy = library yang di khususkan untuk mengolah proses matematika

import numpy as np
data = np.array([1,2,3,4,5])
print(data)

[1 2 3 4 5]


In [14]:
data_2d = np.array([[1,2,3],[4,5,6]])
print(data_2d)
print(data_2d[0])
print(data_2d[0][1])

[[1 2 3]
 [4 5 6]]
[1 2 3]
2


In [15]:
data_3d = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,2,9]
    ],
    [
        [7,8,9],
        [10,11,12],
        [3,5,6]
    ]
])

print(data_3d)
print(data_3d[0])
print(data_3d[0][1])
print(data_3d[0][1][2])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  2  9]]

 [[ 7  8  9]
  [10 11 12]
  [ 3  5  6]]]
[[1 2 3]
 [4 5 6]
 [7 2 9]]
[4 5 6]
6


In [16]:
# fungsi data shape

print(data.shape)
print(data_2d.shape)
print(data_3d.shape)

(5,)
(2, 3)
(2, 3, 3)


In [17]:
# fungsi data ndim

print(data.ndim)
print(data_2d.ndim)
print(data_3d.ndim)

1
2
3


In [18]:
print(data.size)
print(data_2d.size)
print(data_3d.size)

5
6
18


In [20]:
data_2d = np.array([
    [10,20,30],

    [5,10,20],

    [2,4,6]
])
print(data_2d)


[[10 20 30]
 [ 5 10 20]
 [ 2  4  6]]


In [26]:
data_3d = np.array([
    [
        [10,11,12],
        [13,14,15],
        [16,17,18]
    ],
    [
        [20,21,22],
        [23,24,25],
        [26,27,28]
    ],
    [
        [30,31,32],
        [33,34,35],
        [36,37,38]
    ]
])

print(data_3d)

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[20 21 22]
  [23 24 25]
  [26 27 28]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]]]
